import './style/style.css'
import './style/responsive.css'
import HeaderComponent from './components/layouts/HeaderComponent'
import FooterComponent from './components/layouts/FooterComponent'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderComponent/>
        {children}
        <FooterComponent/>
        
      </body>
    </html>
  )
}
